### ISSUE TITLE
Register API issue

### ISSUE THREAD

**Issue by dhruvsh-1729** [Pranay-Pandey/hrm#1]
I think we have not checked in our api if the aadhar already exists for particular doctor or patient when we are registering, it might happen that we will enter duplicate entries for the same aadhar number.

**Comment by Pranay-Pandey** [comment]
No I don't think that is the issue here. Before adding the patient in our smart contract we are checking if that user exists or not.

In the [contract](https://github.com/Pranay-Pandey/hrm/blob/main/contract/hrm_updated.py) we can see the line 
```
@sp.entrypoint
def addPatient(self, param):
           assert self.data.patient_info.contains(param.userAadhar)==False, "User Already Exists"         
```

This ensures that this entrypoint will work only if the user does not already exists. 
Since in the frontend we are using SHA256 hashing for one particular aadhar, the same aadhar when hashed will give the same hash, **ensuring that one particular user cannot register again.** 

Though we are not using hashing for the doctor, it implies that one doctor can register both as a patient and as a doctor, but even then he/she will **not be able to re-register**.
